# 1. Array Vs List Comparison

In [1]:
import numpy as np

In [2]:
lst = [2,4,5,56]
print(type(lst))

<class 'list'>


In [3]:
arr = np.array([1,394,55])
# print(type(arr))
a = arr.tolist()
print(a)
print(sorted(a))

[1, 394, 55]
[1, 55, 394]


## 2. Adding elements in an Array vs List

In [4]:
lst = [89,24,53,898]
arr = np.array([29,244,2344])


In [5]:
lst.append(89)
lst

[89, 24, 53, 898, 89]

In [6]:
np.append(arr,89)

array([  29,  244, 2344,   89])

## 3. Remove elements in an Array vs List

In [7]:
lst = [89,24,53,898]
arr = np.array([29,244,2344])
# lst.pop()
# del lst[-1]
# lst
print("------")
np.delete(arr,-1)
arr

------


array([  29,  244, 2344])

# 4. Updating element Array vs List

In [8]:
lst = [89,24,53,898]
lst[0] = 80
lst[1] = 77
print(lst)

[80, 77, 53, 898]


In [9]:
arr = np.array([1,2,3])
arr[0] = 10
arr[1] = 20
arr[2] = 30
arr

array([10, 20, 30])

# 5.Array vs List Comparsion

In [10]:
import time

In [11]:
#Creating the Data
my_list =  list(range(100000))
my_arr = np.arange(100000)


# Search Time for list
time.time()

1746369360.1804523

In [12]:
my_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
my_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# WS CUBE TEch

In [14]:
import numpy as np

In [15]:
%timeit np.arange(1,9) ** 4

2.15 µs ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## 1. Creating Numpy Arrays

In [16]:
arr = np.array([1,4,6,4,6,7,])
print(arr)
print(type(arr))

[1 4 6 4 6 7]
<class 'numpy.ndarray'>


## List

In [17]:
l = list(range(1,11))
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [18]:
# # Array
# l = []

# for _ in range(5):
#     a = int(input("enter the number : "))
#     l.append(a)
# print(np.array(l))

## Dimension In Arrays
1. 1-D Arrays
2. 2-D Arrays
3. 3-D Arrays
4. Higher Dimensional Arrays

In [19]:
#Check Dimension in the data
arr = np.array([1,4,6,4,6,7,])
print(arr)
print(type(arr))   #check type
print(arr.ndim)    #check dimension

[1 4 6 4 6 7]
<class 'numpy.ndarray'>
1


In [20]:
# 2-D Array

arr2 = np.array([[1,2,3],[5,6,7]])
print(arr2)


[[1 2 3]
 [5 6 7]]


In [21]:
# 3-D Array

arr3 = np.array([[[1,2,3],[5,6,7],[2,5,8]]])
print(arr3)

[[[1 2 3]
  [5 6 7]
  [2 5 8]]]


In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
l = [j**4 for j in range(1,9)]
l

[1, 16, 81, 256, 625, 1296, 2401, 4096]

In [24]:
%timeit [j**4 for j in range(1,9)]

544 ns ± 5.12 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
import numpy as np
%timeit np.arange(2, 20)

669 ns ± 18.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
