In [1]:
import numpy as np

In [3]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [55]:
list  = []
for i in arr:
    for j in i:
        for k in j:
            list.append(k)

In [26]:
arr.dtype

dtype('int32')

In [21]:
arr.ndim

3

In [27]:
arr.astype(np.float64)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [28]:
arr.dtype

dtype('int32')

In [22]:
for i in list:
    print(f"{i} is {type(i)}")

1 is <class 'numpy.int32'>
2 is <class 'numpy.int32'>
3 is <class 'numpy.int32'>
4 is <class 'numpy.int32'>
5 is <class 'numpy.int32'>
6 is <class 'numpy.int32'>
7 is <class 'numpy.int32'>
8 is <class 'numpy.int32'>
9 is <class 'numpy.int32'>
10 is <class 'numpy.int32'>
11 is <class 'numpy.int32'>
12 is <class 'numpy.int32'>


In [29]:
import seaborn as sns

In [32]:
df = sns.load_dataset("titanic")

In [34]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [38]:
df['age'].dtype

dtype('float64')

In [39]:
df['age'].isnull().sum()

177

In [40]:
df['age'] = df['age'].fillna(df['age'].mean())

In [41]:
df['age'] = df['age'].astype(np.int64)

In [42]:
df['age'].dtype

dtype('int64')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    int64   
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(1), int64(5), object(5)
memory usage: 80.7+ KB


In [46]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [50]:
df['deck'].unique()

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [51]:
df['deck'] = df[['deck']].fillna(df['deck'].mode()[0])

In [52]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [56]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [59]:
arr1 = np.array(list)

In [60]:
arr1.mean()

6.5

In [61]:
print(arr1 * 8)

[ 8 16 24 32 40 48 56 64 72 80 88 96]


In [62]:
np.var(arr1)

11.916666666666666

In [63]:
np.size(arr1)

12