## Creating Array

In [1]:
import numpy as np

In [2]:
x = [1,3,5,67]
y = np.array(x)
y

array([ 1,  3,  5, 67])

In [3]:
# Check type of array
type(y)

numpy.ndarray

## Dimensions in Arrays
- 1. 1-D Arrays
- 2. 2-D Arrays
- 3. 3-D Arrays
- 4. Multi-Dimensional Arrays

In [4]:
# Check dimensions in arrays
print(y.ndim)

1


In [5]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [6]:
print(ar2.ndim)

2


In [7]:
arr3 = np.array([[[2,3,4],[3,4,5],[6,7,8]]])
arr3

array([[[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]]])

In [8]:
print(arr3.ndim)

3


## Create Numpy Array Using Numpy Functions

#### Spacial NumPy Arrays
- 1. Array filled with 0
- 2. Array filled with 1
- 3. Create an empty array
- 4. An array with a range of elements
- 5. Array diagonal elements filled with 1
- 6. Create an array with values that are spaced linearlyin a specified interval

### Zeros

In [9]:
arr = np.zeros(10)
arr_zero1 = np.zeros((3,4))
arr_zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ones

In [10]:
arr_1 = np.ones((3,5))
arr_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Empty

In [11]:
ar_em = np.empty(4)
ar_em

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.06811083e-306])

### Range

In [12]:
ar_rn = np.arange(10)
ar_rn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Diagonal

In [13]:
ar_dia = np.eye(9)
ar_dia

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Linspace

In [14]:
ar_lin = np.linspace(0, 10, num=4)
ar_lin

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## 2. Create NumPy Arrays with Random Numbers

- 1. rand()
- 2. randn()
- 3. ranf()
- 4. randint()

### rand()

In [15]:
var  = np.random.rand(20)
var

array([0.83333693, 0.47278771, 0.27377369, 0.45376444, 0.72302519,
       0.62284949, 0.34600978, 0.92079332, 0.77463934, 0.53629813,
       0.49298284, 0.98643129, 0.97514797, 0.74411503, 0.48556229,
       0.62631462, 0.17444818, 0.7228694 , 0.00245694, 0.41179735])

In [16]:
var1 = np.random.rand(5,8)
var1

array([[0.60652206, 0.05319147, 0.99070421, 0.87479314, 0.9378781 ,
        0.31786631, 0.16615187, 0.06640831],
       [0.00383525, 0.81587783, 0.79949744, 0.06684848, 0.26057778,
        0.09751614, 0.66595712, 0.29781096],
       [0.25666804, 0.55317372, 0.40433072, 0.04932239, 0.75403147,
        0.21343263, 0.5013941 , 0.48799378],
       [0.0310425 , 0.49697242, 0.6421721 , 0.48765902, 0.1870064 ,
        0.80531108, 0.37795338, 0.1907435 ],
       [0.32711818, 0.59573872, 0.64021359, 0.51622467, 0.33123535,
        0.82139764, 0.19209161, 0.79043084]])

### randn()

In [17]:
var2 = np.random.randn(5)
var2

array([ 0.42359543,  0.79435304, -0.53983679, -0.38939365, -0.42070251])

### ranf()

In [18]:
var3 = np.random.ranf((2,4))
var3

array([[0.95458344, 0.91035875, 0.44338864, 0.66699082],
       [0.09364683, 0.42260908, 0.85556063, 0.53667555]])

### randint()

In [19]:
var4 = np.random.randint(2, 20,100)
var4

array([ 6,  3,  5,  5, 15, 10,  3, 11, 18, 17,  2, 11, 11,  8, 15,  7, 14,
        4, 17,  7, 17,  9,  9, 12, 17, 15,  2,  3, 13, 12, 18,  5,  9, 15,
       11,  9,  7, 13, 18, 10,  8,  4,  9, 19, 13,  7,  7, 16,  7, 18, 15,
       14, 11,  3, 15,  9, 18, 16,  6,  8, 16,  5, 19,  7,  9,  8, 15,  5,
        2,  5, 12, 18, 16,  2, 14,  3,  4, 18, 12,  9, 17,  3, 16, 10,  2,
        6,  8, 12, 19,  4, 18,  6, 14, 16,  9,  3,  2, 16, 16, 17])

# 3. Data Types in NumPy Arrays

In [20]:
# check data types in numpy array to use dtype

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr.dtype

dtype('int32')

In [22]:
arr.astype(bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Convert data types in sort term

In [24]:
x1 = np.array([1,2,3,4,5], dtype="f")
x1

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
print(x1.dtype)

float32


# 4. Shape & Reshaping in Numpy Arrays

In [26]:
arr = np.random.rand(2,2)
arr

array([[0.29951295, 0.0174592 ],
       [0.0756002 , 0.60185846]])

In [27]:
# Check shape
arr.shape

(2, 2)

In [28]:
var1 = np.array(arr, ndmin=4)
var1

array([[[[0.29951295, 0.0174592 ],
         [0.0756002 , 0.60185846]]]])

### Reshape

In [29]:
ar = np.array([1,2,34,5,67,67,8,9,6])
x = ar.reshape(3,3)
print(x)

[[ 1  2 34]
 [ 5 67 67]
 [ 8  9  6]]


# 5. Arithmetic Operation in NumPy Arrays

- 1. Addition of two arrays:
- 2. Subtraction of two arrays:
- 3. Multiplication of two arrays:
- 4. Division of two arrays:
- 5. np.mod(a,b)
- 6. np.power(a,b)
- 7. np.sqrt(a)
- 8. np.reciprocal(a)

### addition()

In [30]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = var1 + var2
print(add)

[ 6  8 10 12]


### subtraction()

In [31]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = var1 - var2
print(add)

[-4 -4 -4 -4]


# 6. Arithmetic Functions
- 1. np.min(x)
- 2. np.max(x)
- 3. np.argmin(x)
- 4. np.sqrt()
- 5. np.sin(x)
- 6. np.cos(x)
- 7. np.cumsum()

In [32]:
arr = np.arange(20)
new = arr.copy()
new


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
print(np.min(new))

0


In [35]:
print(np.max(new))

19


In [36]:
np.argmin(new)

0

In [37]:
np.argmax(new)

19

In [38]:
# If have two or more column and row
var1 = np.array([[2,3,5],[9,3,6]])
re = np.min(var1, axis=0)
re

array([2, 3, 5])

# 7. Broadcasting NumPy Arrays

# 8. Slice and Slicing

# 9. Iterating Numpy Arrays

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
l = [i**2 for i in arr]
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [41]:
a = np.array([[[2,4,5,6],[6,7,8,3]]])
a.ndim

3

In [42]:
for i in a:
    for j in i:
        for k in j:
            print(k)

2
4
5
6
6
7
8
3


In [43]:
# Easy way to iterating
for i in np.nditer(a):
    print(i)

2
4
5
6
6
7
8
3


In [44]:
# Also know the index value using ndenumerate()

for i in np.ndenumerate(a):
    print(i)

((0, 0, 0), 2)
((0, 0, 1), 4)
((0, 0, 2), 5)
((0, 0, 3), 6)
((0, 1, 0), 6)
((0, 1, 1), 7)
((0, 1, 2), 8)
((0, 1, 3), 3)


# 10 . Copy VS View in NumPy Arrays

In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[1] = 8

In [47]:
c = arr.copy()
c

array([0, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
v = arr.view()
v

array([0, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
v

array([0, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
c

array([0, 8, 2, 3, 4, 5, 6, 7, 8, 9])

# 11. Join & Spilt NumPy Arrays Functions

In [51]:
var = np.arange(10)
var1 = np.arange(10)
arr = np.concatenate((var,var1))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
var = np.array([1,2,3,4,5,6])
print(var)

ar = np.array_split(var,3)
print(ar)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


# 12. NumPy Arrays Functions ( Search, Sort, Search Sorted, Filter)

#### Search

In [53]:
var = np.array([2,3,4,6,72,5,2,6,2,9])
var

array([ 2,  3,  4,  6, 72,  5,  2,  6,  2,  9])

In [54]:
x = np.where(var == 2) # find the index of the element that is 2
print(x)

(array([0, 6, 8], dtype=int64),)


### Search Sorted Array

In [55]:
var1 = np.array([1,2,3,4,5,6,7,8])
x1 = np.searchsorted(var1,5)
print(x1)

4


In [56]:
var1

array([1, 2, 3, 4, 5, 6, 7, 8])

## Sort

In [57]:
var1 = np.array([10,20,32,14,50,16,27,8])
re = np.sort(var1)
re

array([ 8, 10, 14, 16, 20, 27, 32, 50])

## Filter Array

# 13. Shuffle, Unique , Resize, Flatten, Ravel Functions

In [58]:
arr = np.array([2,5,6,7,8,9])
a = np.random.shuffle(arr)
arr

array([6, 7, 2, 9, 8, 5])

In [59]:
arr = np.array([2,5,6,7,8,9,2,7])
a = np.unique(arr, return_counts=True)
a

(array([2, 5, 6, 7, 8, 9]), array([2, 1, 1, 2, 1, 1], dtype=int64))

In [60]:
arr = np.array([2,5,6,7,8,9])

# 14. NumPy Arrays Functions ( Insert and Delete Function)

In [61]:
# Insert


var = np.array([2,5,6,7,8])
print(var)

[2 5 6 7 8]


In [62]:
np.insert(var,-1,50)

array([ 2,  5,  6,  7, 50,  8])

### Insert value in 2-D array

In [63]:
var1 = np.array([[1,2,3],[4,5,6]])
np.insert(var1,1,90, axis=1)


array([[ 1, 90,  2,  3],
       [ 4, 90,  5,  6]])

In [64]:
# Using append() Function


np.append(var, 7)

array([2, 5, 6, 7, 8, 7])

### Delete

In [65]:
var = np.array([2,5,6,7,8])

In [66]:
np.delete(var,np.where(var == 5))

array([2, 6, 7, 8])

# 15. NumPy--Matrix

In [67]:
mat = np.matrix([[2,3,4],[1,2,3]])
mat

print(type(mat))

<class 'numpy.matrix'>


# 16. Matrix Functions in NumPy Arrays