## Creating Array

In [2]:
import numpy as np

In [5]:
x = [1,3,5,67]
y = np.array(x)
y

array([ 1,  3,  5, 67])

In [7]:
# Check type of array
type(y)

numpy.ndarray

## Dimensions in Arrays
- 1. 1-D Arrays
- 2. 2-D Arrays
- 3. 3-D Arrays
- 4. Multi-Dimensional Arrays

In [8]:
# Check dimensions in arrays
print(y.ndim)

1


In [9]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [10]:
print(ar2.ndim)

2


In [11]:
arr3 = np.array([[[2,3,4],[3,4,5],[6,7,8]]])
arr3

array([[[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]]])

In [12]:
print(arr3.ndim)

3


## Create Numpy Array Using Numpy Functions

#### Spacial NumPy Arrays
- 1. Array filled with 0
- 2. Array filled with 1
- 3. Create an empty array
- 4. An array with a range of elements
- 5. Array diagonal elements filled with 1
- 6. Create an array with values that are spaced linearlyin a specified interval

### Zeros

In [16]:
arr = np.zeros(10)
arr_zero1 = np.zeros((3,4))
arr_zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ones

In [25]:
arr_1 = np.ones((3,5))
arr_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Empty

In [18]:
ar_em = np.empty(4)
ar_em

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.06811083e-306])

### Range

In [27]:
ar_rn = np.arange(10)
ar_rn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Diagonal

In [21]:
ar_dia = np.eye(9)
ar_dia

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Linspace

In [23]:
ar_lin = np.linspace(0, 10, num=4)
ar_lin

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## 2. Create NumPy Arrays with Random Numbers

- 1. rand()
- 2. randn()
- 3. ranf()
- 4. randint()

### rand()

In [30]:
var  = np.random.rand(20)
var

array([0.88042478, 0.00803852, 0.71491944, 0.10741603, 0.52259166,
       0.4888128 , 0.28573277, 0.584253  , 0.80451134, 0.06558047,
       0.03662227, 0.37620297, 0.62619851, 0.74225251, 0.56075208,
       0.96094547, 0.57512275, 0.1738552 , 0.19482435, 0.9210475 ])

In [32]:
var1 = np.random.rand(5,8)
var1

array([[0.85312473, 0.65459795, 0.18822595, 0.27567771, 0.41708608,
        0.24853419, 0.87936349, 0.02854701],
       [0.55490867, 0.38920054, 0.37139756, 0.20632136, 0.63596619,
        0.62953456, 0.96750717, 0.09187015],
       [0.45516583, 0.96889533, 0.61034008, 0.82434432, 0.16391031,
        0.9234824 , 0.3704984 , 0.48408517],
       [0.85462711, 0.02050926, 0.10864764, 0.24392326, 0.89345484,
        0.17558699, 0.09985936, 0.49584818],
       [0.62447728, 0.73257081, 0.51403757, 0.40702027, 0.02147236,
        0.88587087, 0.36995043, 0.40723158]])

### randn()

In [33]:
var2 = np.random.randn(5)
var2

array([ 2.01108647, -0.23651975,  0.8294703 , -1.4251863 ,  0.05217959])

### ranf()

In [35]:
var3 = np.random.ranf((2,4))
var3

array([[0.91538988, 0.16974493, 0.50752581, 0.25273464],
       [0.820739  , 0.20832651, 0.99885009, 0.31844248]])

### randint()

In [37]:
var4 = np.random.randint(2, 20,100)
var4

array([ 6, 15, 16, 11,  2,  5,  7, 16, 17,  4,  2,  9,  4, 13, 15, 12,  2,
        3, 11, 15,  3, 12, 17, 13,  4, 10, 17, 14, 12, 12, 17,  5, 19, 13,
        7,  3, 17, 11, 19,  5, 19, 13,  8, 12,  8, 18, 12, 13,  4,  5, 16,
       11, 11, 10,  5,  9,  4, 10,  7, 10,  9, 10, 19,  5, 13,  6, 11, 15,
       18, 14, 10, 18,  3, 19, 12, 17,  8, 14, 12,  5,  2,  5, 16,  4,  7,
        7,  4,  5,  8, 10,  8, 15, 10, 14, 12,  9, 17,  9,  3,  7])

# 3. Data Types in NumPy Arrays

In [43]:
# check data types in numpy array to use dtype

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr.dtype

dtype('int32')

In [47]:
arr.astype(bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Convert data types in sort term

In [48]:
x1 = np.array([1,2,3,4,5], dtype="f")
x1

array([1., 2., 3., 4., 5.], dtype=float32)

In [49]:
print(x1.dtype)

float32


# 4. Shape & Reshaping in Numpy Arrays

In [54]:
arr = np.random.rand(2,2)
arr

array([[0.93886503, 0.28904231],
       [0.88632314, 0.17626252]])

In [55]:
# Check shape
arr.shape

(2, 2)

In [58]:
var1 = np.array(arr, ndmin=4)
var1

array([[[[0.93886503, 0.28904231],
         [0.88632314, 0.17626252]]]])

### Reshape

In [62]:
ar = np.array([1,2,34,5,67,67,8,9,6])
x = ar.reshape(3,3)
print(x)

[[ 1  2 34]
 [ 5 67 67]
 [ 8  9  6]]


# 5. Arithmetic Operation in NumPy Arrays

- 1. Addition of two arrays:
- 2. Subtraction of two arrays:
- 3. Multiplication of two arrays:
- 4. Division of two arrays:
- 5. np.mod(a,b)
- 6. np.power(a,b)
- 7. np.sqrt(a)
- 8. np.reciprocal(a)

### addition()

In [63]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = var1 + var2
print(add)

[ 6  8 10 12]


### subtraction()

In [64]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = var1 - var2
print(add)

[-4 -4 -4 -4]


# 6. Arithmetic Functions
- 1. np.min(x)
- 2. np.max(x)
- 3. np.argmin(x)
- 4. np.sqrt()
- 5. np.sin(x)
- 6. np.cos(x)
- 7. np.cumsum()

In [70]:
arr = np.arange(20)
new = arr.copy()
new


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
print(np.min(new))

0


In [73]:
print(np.max(new))

19


In [74]:
np.argmin(new)

0

In [75]:
np.argmax(new)

19

In [77]:
# If have two or more column and row
var1 = np.array([[2,3,5],[9,3,6]])
re = np.min(var1, axis=0)
re

array([2, 3, 5])

# 7. Broadcasting NumPy Arrays

# 8. Slice and Slicing

# 9. Iterating Numpy Arrays

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
l = [i**2 for i in arr]
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [83]:
a = np.array([[[2,4,5,6],[6,7,8,3]]])
a.ndim

3

In [86]:
for i in a:
    for j in i:
        for k in j:
            print(k)

2
4
5
6
6
7
8
3


In [90]:
# Easy way to iterating
for i in np.nditer(a):
    print(i)

2
4
5
6
6
7
8
3


In [92]:
# Also know the index value using ndenumerate()

for i in np.ndenumerate(a):
    print(i)

((0, 0, 0), 2)
((0, 0, 1), 4)
((0, 0, 2), 5)
((0, 0, 3), 6)
((0, 1, 0), 6)
((0, 1, 1), 7)
((0, 1, 2), 8)
((0, 1, 3), 3)


# 10 . Copy VS View in NumPy Arrays

In [99]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr[1] = 8

In [104]:
c = arr.copy()
c

array([ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9])

In [101]:
v = arr.view()
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
v

array([0, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
c

array([ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9])

# 11. Join & Spilt NumPy Arrays Functions

In [109]:
var = np.arange(10)
var1 = np.arange(10)
arr = np.concatenate((var,var1))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
var = np.array([1,2,3,4,5,6])
print(var)

ar = np.array_split(var,3)
print(ar)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


# 12. NumPy Arrays Functions ( Search, Sort, Search Sorted, Filter)

#### Search

In [113]:
var = np.array([2,3,4,6,72,5,2,6,2,9])
var

array([ 2,  3,  4,  6, 72,  5,  2,  6,  2,  9])

In [114]:
x = np.where(var == 2) # find the index of the element that is 2
print(x)

(array([0, 6, 8], dtype=int64),)


### Search Sorted Array

In [118]:
var1 = np.array([1,2,3,4,5,6,7,8])
x1 = np.searchsorted(var1,5)
print(x1)

4


In [119]:
var1

array([1, 2, 3, 4, 5, 6, 7, 8])

## Sort

In [120]:
var1 = np.array([10,20,32,14,50,16,27,8])
re = np.sort(var1)
re

array([ 8, 10, 14, 16, 20, 27, 32, 50])

## Filter Array

# 13. Shuffle, Unique , Resize, Flatten, Ravel Functions

In [133]:
arr = np.array([2,5,6,7,8,9])
a = np.random.shuffle(arr)
arr

array([9, 5, 6, 2, 8, 7])

In [135]:
arr = np.array([2,5,6,7,8,9,2,7])
a = np.unique(arr, return_counts=True)
a

(array([2, 5, 6, 7, 8, 9]), array([2, 1, 1, 2, 1, 1], dtype=int64))

In [ ]:
arr = np.array([2,5,6,7,8,9])

# 14. NumPy Arrays Functions ( Insert and Delete Function)

In [143]:
# Insert


var = np.array([2,5,6,7,8])
print(var)

[2 5 6 7 8]


In [146]:
np.insert(var,-1,50)

array([ 2,  5,  6,  7, 50,  8])

### Insert value in 2-D array

In [141]:
var1 = np.array([[1,2,3],[4,5,6]])
np.insert(var1,1,90, axis=1)


array([[ 1, 90,  2,  3],
       [ 4, 90,  5,  6]])

In [148]:
# Using append() Function


np.append(var, 7)

array([2, 5, 6, 7, 8, 7])

### Delete

In [149]:
var = np.array([2,5,6,7,8])

In [151]:
np.delete(var,np.where(var == 5))

array([2, 6, 7, 8])

# 15. NumPy--Matrix

In [154]:
mat = np.matrix([[2,3,4],[1,2,3]])
mat

print(type(mat))

<class 'numpy.matrix'>


# 16. Matrix Functions in NumPy Arrays