## Importing / Exporting

In [1]:
import numpy as np

## Creating Arrays

In [2]:
arr  = np.array([1,2,3,4])  # One dimensional Array
print(arr)

[1 2 3 4]


In [3]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])  # Two Dimensional Array
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
np.zeros(3) # 1-D Array of length 3 all values 0

array([0., 0., 0.])

In [5]:
np.ones((3,4)) # 3x4 array with all values 1.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(5) #5x5 array of 0 with 1 on diagonal(identity matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.linspace(0,100) # Array of 6 evenly divided values from 0  to 100

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.random.rand(4,5) # 4x5 array of random floats between 0-1

array([[0.36621014, 0.81539049, 0.3811785 , 0.54150168, 0.89820478],
       [0.88718276, 0.65585766, 0.10703076, 0.1912463 , 0.16586974],
       [0.6180771 , 0.62510934, 0.66645612, 0.92612052, 0.05872147],
       [0.789812  , 0.66029299, 0.95203289, 0.10849776, 0.60553269]])

In [10]:
np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0-4

array([[2, 4, 3],
       [3, 4, 2]])

## Inspecting Properties

In [11]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.size # Returns numbers of elements in arr

10

In [13]:
arr.shape # Returns numbers of arr(rows, columns)

(10,)

In [14]:
arr.dtype # Returns types of elements in arr

dtype('int32')

In [15]:
arr.astype(int) # Convert arr elements to type dtype.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.tolist() # Convert arr to a Python list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.info(np.eye(20))  # VIew documents for np-eye

class:  ndarray
shape:  (20, 20)
strides:  (160, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1eb97245030
byteorder:  little
byteswap:  False
type: float64


## Copying/Sorting/Reshaping

In [18]:
arr1 = np.linspace(0,20)
arr1

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [19]:
b = np.copy(arr1) # Coples arr to new memory
b

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [20]:
arr1.astype(object)

array([0.0, 0.40816326530612246, 0.8163265306122449, 1.2244897959183674,
       1.6326530612244898, 2.0408163265306123, 2.4489795918367347,
       2.857142857142857, 3.2653061224489797, 3.673469387755102,
       4.081632653061225, 4.4897959183673475, 4.8979591836734695,
       5.3061224489795915, 5.714285714285714, 6.122448979591837,
       6.530612244897959, 6.938775510204081, 7.346938775510204,
       7.755102040816327, 8.16326530612245, 8.571428571428571,
       8.979591836734695, 9.387755102040817, 9.795918367346939,
       10.204081632653061, 10.612244897959183, 11.020408163265307,
       11.428571428571429, 11.83673469387755, 12.244897959183675,
       12.653061224489797, 13.061224489795919, 13.46938775510204,
       13.877551020408163, 14.285714285714286, 14.693877551020408,
       15.10204081632653, 15.510204081632654, 15.918367346938776,
       16.3265306122449, 16.73469387755102, 17.142857142857142,
       17.551020408163264, 17.95918367346939, 18.367346938775512,
       18.7

In [21]:
arr1.view(int)

array([          0,           0,  -788871544,  1071259480,  -788871544,
        1072308056, -1665395482,  1072928642,  -788871544,  1073356632,
       -2103657451,  1073763223, -1665395482,  1073977218, -1227133513,
        1074191213,  -788871544,  1074405208,  -350609575,  1074619203,
       -2103657451,  1074811799,   262957182,  1074918797, -1665395482,
        1075025794,   701219150,  1075132792, -1227133513,  1075239789,
        1139481120,  1075346787,  -788871544,  1075453784,  1577743088,
        1075560782,  -350609575,  1075667779,  2016005058,  1075774777,
       -2103657451,  1075860375,  1227133513,  1075913874,   262957182,
        1075967373,  -701219150,  1076020871, -1665395482,  1076074370,
        1665395482,  1076127869,   701219150,  1076181368,  -262957181,
        1076234866, -1227133513,  1076288365,  2103657451,  1076341864,
        1139481120,  1076395363,   175304788,  1076448862,  -788871544,
        1076502360, -1753047876,  1076555859,  1577743088,  1076

In [22]:
arr1.sort()  #Sorts arr

In [23]:
arr1.sort(axis=0) # Sorts specific axis of arr

In [24]:
# arr.reshape(3,4) # Reshapes to 3 rows , 4 columns without changing data

In [25]:
# arr.resize(5,6) # Changes arr shape to 5x6 and fills new values with}| 0

## Adding / Removing Elements

In [26]:
arr  = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.append(arr,90) # Appends values to the end of arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 90])

In [28]:
np.insert(arr,2,100) # Insert values into arr before index 2

array([  1,   2, 100,   3,   4,   5,   6,   7,   8,   9])

In [29]:
np.delete(arr,3,axis=0) # Delete row on index 3 of arr

array([1, 2, 3, 5, 6, 7, 8, 9])

In [30]:
np.delete(arr,5,axis=1) # Deletes column on index 4 of arr

AxisError: axis 1 is out of bounds for array of dimension 1

## Combining/Splitting

In [76]:
arr1 = np.linspace(1,20)
arr2 = np.linspace(1,20)

In [78]:
np.concatenate((arr1,arr2),axis=0) # Adds arr2 as rows to the end of arr1

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ,
        1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36

In [79]:
np.concatenate((arr1,arr2), axis=1) # Adds arr2 as columns to end of arr1

AxisError: axis 1 is out of bounds for array of dimension 1

In [80]:
np.split(arr1,3)

ValueError: array split does not result in an equal division

## Indexing/Slicing / Subsetting

In [114]:
arr  = np.array([np.arange(1,10)],[np.arange(1,10)])
arr

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [112]:
arr[5] # Returns the elements at index 5

6

In [113]:
arr[2,5] # Returns the 2-D array elements on index [2][5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [31]:
arr[1] = 4 # Assigns array elements on index 1 the value 4

In [32]:
arr

array([1, 4, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1,3] = 10 # Assigns array element on index [1][3] the value 10

## Acalar MATH

In [34]:
arr  = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.add(arr,1) # Add 1 to each array element

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.subtract(arr,2) # Subtract 2 from each array element by 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [38]:
np.multiply(arr,3) # Multiply each array element by 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
np.divider(arr,4) # Divide each array element by 4 (returns np.nan for division by zero)

AttributeError: module 'numpy' has no attribute 'divider'

In [40]:
np.power(arr,5) # Each array element to the 5th power

array([    1,    32,   243,  1024,  3125,  7776, 16807, 32768, 59049],
      dtype=int32)

## VECTOR MATH

In [44]:
arr  = np.arange(1,10)
arr1  = np.arange(1,10)


In [46]:
np.add(arr,arr1) # Element add arr2 to arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
np.subtract(arr,arr1) # Elements subtract arr1 from arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.multiply(arr,arr1) # Elements multiply arr by arr1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
np.divide(arr,arr1) # Element divide arr by arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.power(arr,arr1) # ELements arr to the power of arr1

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])

## STATISTICS

In [54]:
np.mean(arr,axis=0) # Returns mean along specific axis

5.0

In [55]:
arr.sum() # Returns sum of arr

45

In [56]:
arr.min() # Returns minimum value of arr

1

In [57]:
arr.max(axis=0) # Returns mazximun value of specific axis

9